import express from "express";
import UserController from "../controllers/user";
import authen from "../middlewares/auth";
const userRouter = express.Router();
userRouter.post("/login", UserController.login);
userRouter.post("/register", UserController.register);
userRouter.post("/get-new-token", UserController.getNewAccessToken);
userRouter.post("/get-user-reload", UserController.getUserInfo);
userRouter.get("/search", UserController.search);
userRouter.use(authen);
userRouter.post("/update", UserController.update);
userRouter.post("/find-user-profile", UserController.findUserProfile);
userRouter.post("/add-friend", UserController.addFriend);
userRouter.post("/get-notify", UserController.getNotify);
userRouter.post("/get-friend", UserController.getFriend);
userRouter.post("/get-friendship", UserController.getFriendShip);
userRouter.post("/cancel-friendship", UserController.cancelFriendShip);
userRouter.post("/seen-notify", UserController.seenNotify);
userRouter.post("/unfriend", UserController.unFriend);

export default userRouter;
